version: "3.3"
services:
  dev:
    image: euler_dev:1.0
    ports:
      - "9999:22"
    networks:
      dev:
        ipv4_address: 172.18.0.100
    volumes:
      - ~/code:/home/code
      - ~/app/vscode-euler:/root/.vscode-server
  ubuntu:
    image: ubuntu:1.0
    ports:
      - "9998:22"
    networks:
      dev:
        ipv4_address: 172.18.0.99
    volumes:
      - ~/code:/home/code
      - ~/app/vscode-euler:/root/.vscode-server
  jenkins:
    image: jenkins:2.210
    ports:
      - "8088:8080"
    volumes:
      - ~/jenkins:/var/jenkins_home
      - ~/code:/home/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
  gitbook:
    image: gitbook:1.0
    ports:
      - "4000:4000"
    volumes:
      - ~/code/shoppon.github.io:/home/pages
    command: bash -c "cd /home/pages && gitbook install && gitbook build && gitbook serve"
  gitbook_build:
    image: gitbook:1.0
    volumes:
      - ~/code/shoppon.github.io:/home/pages
    command: bash -c "cd /home/pages && gitbook install && gitbook build"
  manictime:
    image: manictime:latest
    volumes:
      - /Users/shoppon/software/manictimeserver/Data:/app/Data
    ports:
      - "8080:8080"
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
